create table board(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(255),
    primary key (id)
);

create table member(
    mId bigint generated by default as identity,
    userId varchar(30),
    password varchar(30),
    primary key(mId);
);